name: Sync

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 6 * * 1,3,5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure git
        run: |
          git config --global push.default simple
          git config --global user.name "actions"
          git config --global user.email "actions@openmicroanalysis.org"
          git config --global core.ignorecase true
          git remote set-url --push origin git@github.com:openmicroanalysis/calczaf.git
      - name: Synchronize
        run: python .github/sync.py --verbose --no-pull --no-push --workdir .
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

